#!/bin/bash

mkdir -p /app/data
cd /app

if [ ! -d "data/master" ]; then
  buildbot create-master data/master
  mv data/master/master.cfg.sample data/master/master.cfg

  echo "Configuration file has been created in /app/data/master.cfg."
  echo "Please adjust the file to your likings and restart this container."
else
  buildbot start --nodaemon data/master
fi
